add part 6 code
taronsaribekyan1998/ToDoList pull request #7
Opened 2021-12-17 14:04 UTC by taronsaribekyan1998

2021-12-30 11:18 UTC, hovaks requested changes

2021-12-30 11:18 UTC, hovaks commented on ViewControllers/ToDoTableViewController.swift
> +        guard segue.identifier == "saveUnwind" else {return}
Curley brace-երի մեջ միշտ space a պետք { return }

2021-12-30 11:18 UTC, hovaks commented on ViewControllers/ToDoTableViewController.swift
> +        let sourceViewController = segue.source as! ToDoDetailTableViewController
Եքյա գարդը գրել ես, մեջը էս տողն էլ ավելացնեիր էլի, ինչի ես ֆորս անրափ արել:

2021-12-30 12:12 UTC, taronsaribekyan1998 commented
Changes added.

2022-01-12 12:07 UTC, hovaks approved these changes

2022-01-12 12:07 UTC, merged